### ISSUE TITLE
Firefox stack trace

### ISSUE THREAD

**Issue by dy** [sindresorhus/extract-stack#2]
Does this package handle the Firefox stack?

Chrome:
```
Error
    at fx (http://localhost:1234/test.e31bb0bc.js:3290:11)
    at HTMLDivElement.<anonymous> (http://localhost:1234/test.e31bb0bc.js:4219:19)
    at callAspect (http://localhost:1234/test.e31bb0bc.js:1088:35)
    at update (http://localhost:1234/test.e31bb0bc.js:1022:3)
    at spect (http://localhost:1234/test.e31bb0bc.js:998:3)
    at Test.fn (http://localhost:1234/test.e31bb0bc.js:4218:16)
    at Test.run (http://localhost:1234/test.e31bb0bc.js:500:14)
    at dequeue (http://localhost:1234/test.e31bb0bc.js:625:18)
    at dequeue (http://localhost:1234/test.e31bb0bc.js:608:14)
    at dequeue (http://localhost:1234/test.e31bb0bc.js:608:14)
```

Firefox:
```
fx@http://localhost:1234/test.e31bb0bc.js:3290:11
parcelRequire<["fx.js"]</</<@http://localhost:1234/test.e31bb0bc.js:4219:19
callAspect@http://localhost:1234/test.e31bb0bc.js:1088:35
update@http://localhost:1234/test.e31bb0bc.js:1022:3
spect@http://localhost:1234/test.e31bb0bc.js:998:3
parcelRequire<["fx.js"]</<@http://localhost:1234/test.e31bb0bc.js:4218:16
run@http://localhost:1234/test.e31bb0bc.js:500:14
dequeue@http://localhost:1234/test.e31bb0bc.js:625:18
```

**Comment by sindresorhus** [comment]
No, it only handles V8 stack traces. But PR welcome to improve this.

**Comment by sindresorhus** [comment]
Passing on this. There are plans to standardize stack, so doesn't make sense to specificallt support Firefox at this time.
